language: python

install:
  - curl -fsSL https://deno.land/x/install/install.sh | sh -s v0.19.0
  - export PATH="$HOME/.deno/bin:$PATH"

script:
  - find test -name \*.js -type f -print0 | xargs -0 -n1 deno
